<%@ Page Title="Actualizare Date" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Actualizare_Date.aspx.cs" Inherits="SalaryCalculator.Actualizare_Date" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
    <p class="titleFont">Actualizare Date</p>
    <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="True" BorderColor="Black" BorderWidth="1px" OnRowCreated="GridView1_RowCreated" OnRowDataBound="GridView1_RowDataBound1" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" OnRowEditing="GridView1_RowEditing" OnSelectedIndexChanged="GridView1_SelectedIndexChanged"  />

    <br />
    <br />

    <div>

        <asp:Label ID="lblInfoText" runat="server" Text="Modificati urmatoarele valori pentru angajatul selectat: " />
        <asp:Label ID="lblNumeSelectat" runat="server" />
   
    </div>
</asp:Content>

